# Generated by Django 6.0.6 on 2026-06-18 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0002_pais_alter_estudiante_id_alter_numerotelefonico_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrativo.pais'),
        ),
    ]
